version: '3.8'

services:
  # PostgreSQL 数据库 (开发环境)
  postgres:
    image: postgres:15-alpine
    container_name: terminal-postgres-dev
    environment:
      POSTGRES_DB: ${DB_DATABASE:-terminal_dev}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - terminal-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_DATABASE:-terminal_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
    driver: local

networks:
  terminal-dev-network:
    driver: bridge
