services:
  # NestJS 服务
  service:
    build:
      context: ../apps/service
      dockerfile: Dockerfile
    container_name: ${DOCKER_CONTAINER_NAME:-terminal-service}
    ports:
      - "${SERVICE_PORT:-3000}:3000"
    env_file:
      - ../env/production.env
    environment:
      - NODE_ENV=production
      - DB_TYPE=${DB_TYPE:-sqlite}
      - DB_DATABASE=${DB_DATABASE:-/app/data/terminal.db}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - PORT=${SERVICE_PORT:-3000}
    volumes:
      - service_data:/app/data
    networks:
      - terminal-network
    restart: unless-stopped

volumes:
  service_data:
    driver: local

networks:
  terminal-network:
    driver: bridge 